(("function" @keyword) (#set! conceal "ƒ"))
(("async" @keyword) (#set! conceal "a"))
(("=>" @keyword) (#set! conceal "⇒"))
(("return" @keyword) (#set! conceal "⇚"))
;; (("comment_start"    @comment) (#set! conceal ""))
